development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= "redis://#{Settings.REDIS.HOST}:#{Settings.REDIS.PORT}/1" %>
  channel_prefix: inventory_vendor_management_production
