
#####################################
########## OPEN API CALLS ###########
#####################################
open permission:
  - 'static#*'

login permission:
  # Feed Calls
  - 'api/public/v1/adjustments#*'
  - 'api/public/v1/put_aways#*'
  - 'api/public/v1/batches#*'
  - 'api/public/v1/inventories#*'
  - 'api/public/v1/inventory_pickups#*'
  - 'api/public/v1/invoices#*'
  - 'api/public/v1/locations#*'
  - 'api/public/v1/material_requests#*'
  - 'api/public/v1/purchase_order_items#*'
  - 'api/public/v1/purchase_orders#*'
  - 'api/public/v1/purchase_receipt_items#*'
  - 'api/public/v1/purchase_receipts#*'
  - 'api/public/v1/sales_order_items#*'
  - 'api/public/v1/sales_orders#*'
  - 'api/public/v1/schemes#*'
  - 'api/public/v1/skus#*'
  - 'api/public/v1/supplier_skus#*'
  - 'api/public/v1/suppliers#*'
  - 'api/public/v1/vendor_supplier_contracts#*'
  - 'api/public/v1/vendor_supplier_schemes#*'
  - 'api/public/v1/vendors#*'
  - 'api/public/v1/pr_item_returns#*'
  - 'api/public/v1/sales_returns#*'

#####################################
####### ROLES REQUIRED CALLS ########
#####################################
roles permission:
  restricted:
    home_read:
      - 'home#index'
    ########################
    ##### AUTH MODULE ######
    ########################
    users_read:
      - 'users#index'
      - 'users#show'
    users_write:
      - 'users#new'
      - 'users#create'
      - 'users#edit'
      - 'users#update'
      - 'users#perform_action'
    users_destroy:
      - 'users#destroy'
    orders_users_write:
      - 'users#new_user'
      - 'users#create_from_order_flow'
    roles_read:
      - 'roles#index'
      - 'roles#show'
    roles_write:
      - 'roles#new'
      - 'roles#create'
      - 'roles#edit'
      - 'roles#update'
    roles_destroy:
      - 'roles#destroy'
    permissions_read:
      - 'permissions#index'
      - 'permissions#show'
    permissions_write:
      - 'permissions#new'
      - 'permissions#create'
      - 'permissions#edit'
      - 'permissions#update'
    permissions_destroy:
      - 'permissions#destroy'
