## TODO: add required routes in this file

#####################################
########## OPEN API CALLS ###########
#####################################
open permission:
  - 'api/public/v1/home#public_index'
  - 'api/public/v1/home#search'
  - 'api/public/v1/home#category'
  - 'api/public/v1/jobs#public_show'
  - 'api/public/v1/users#show'
  - 'api/public/v1/users#create'
  - 'api/public/v1/spam_reports#public_index'

login permission:
  - 'api/public/v1/home#*'
  - 'api/public/v1/users#*'
  - 'api/public/v1/jobs#*'
  - 'api/public/v1/favorite_collections#*'
  - 'api/public/v1/favorites#*'
  - 'api/public/v1/orders#*'
  - 'api/public/v1/payment_transactions#*'
  - 'api/public/v1/spam_reports#*'
  - 'api/public/v1/categories#*'
  - 'api/public/v1/countries#*'
  - 'api/public/v1/skills#*'
  - 'api/public/v1/tags#*'

#####################################
####### ROLES REQUIRED CALLS ########
#####################################
roles permission:
  ########################
  ##### AUTH MODULE ######
  ########################
  action_logs_read:
    - 'action_logs#index'
    - 'action_logs#show'
  action_logs_write:
    - 'action_logs#create'
    - 'action_logs#update'
  action_logs_destroy:
    - 'action_logs#destroy'
  benefits_read:
    - 'benefits#index'
    - 'benefits#show'
  benefits_write:
    - 'benefits#create'
    - 'benefits#update'
  benefits_destroy:
    - 'benefits#destroy'
  categories_read:
    - 'categories#index'
    - 'categories#show'
  categories_write:
    - 'categories#create'
    - 'categories#update'
  categories_destroy:
    - 'categories#destroy'
  countries_read:
    - 'countries#index'
    - 'countries#show'
  countries_write:
    - 'countries#create'
    - 'countries#update'
  countries_destroy:
    - 'countries#destroy'
  roles_read:
    - 'roles#index'
    - 'roles#show'
  roles_write:
    - 'roles#create'
    - 'roles#update'
  roles_destroy:
    - 'roles#destroy'
  permissions_read:
    - 'permissions#index'
    - 'permissions#show'
  permissions_write:
    - 'permissions#create'
    - 'permissions#update'
  permissions_destroy:
    - 'permissions#destroy'
