RAILS:
  SECRET_KEY_BASE: '5453eb34557b1ddcdae8939688b739eb30a7c1b55222c608b866d8509c1450f97c850f07e20ccfbedba06137aefaba8d19e3286aed5673fca0105049562633dd'

PUMA:
  THREADS:
    MIN: 1
    MAX: 5
  WORKERS: 1
  PORT: 3000

PSQL:
  POOL: 5
  HOST: localhost
  PORT: 5432
  USERNAME: sachin
  PASSWORD: s
  DATABASE: broxer_db
  CONNECT_TIMEOUT: 1
  READ_TIMEOUT: 1
  CHECKOUT_TIMEOUT: 1
  STATEMENT_LIMIT: 100

CACHE:
  ENABLE: false
  REDIS:
    HOST: 127.0.0.1
    PORT: 6379
    TIMEOUT: 0.1 # Second
    POOL: 10
    LOGGING: false

PUBSUB:
  ENABLE: false
  REDIS:
    HOST: 127.0.0.1
    PORT: 6379
    TIMEOUT: 0.1 # Second
    LOGGING: false

SYNCHRONIZE:
  ENABLE: false
  REDIS:
    HOST: 127.0.0.1
    PORT: 6379
    LOGGING: false

SIDEKIQ:
  REDIS:
    HOST: 127.0.0.1
    PORT: 6379
  SERVER:
    REDIS:
      POOL: 25
  CLIENT:
    REDIS:
      POOL: 5

AWS:
  AWS_ACCESS_KEY_ID: AKIAIEK2QJW6WMSV2Q3Q
  AWS_SECRET_ACCESS_KEY: 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
  AWS_S3_BUCKET: broxer-development
  AWS_S3_REGION: ap-south-1

OMNIAUTH:
  FACEBOOK_AUTHENTICATION_CLIENT_ID: 241917396562361
  FACEBOOK_AUTHENTICATION_CLIENT_SECRET: f870373c2fa8dfb44ca4d0c24ad028d1
  TWITTER_AUTHENTICATION_CLIENT_ID: mld3XTC6M6j0ZDDRZC4eckazt
  TWITTER_AUTHENTICATION_CLIENT_SECRET: HJ8fmUcLPmy3i37wg71x3M48VGgUxe2XyW7GGDbJ8hL7BsaSVP
  LINKEDIN_AUTHENTICATION_CLIENT_ID: 8180hak9jr5syp
  LINKEDIN_AUTHENTICATION_CLIENT_SECRET: 4s7cTjNlNuK3Loub
  GOOGLE_AUTHENTICATION_CLIENT_ID: 937283752736-tknmt97jl2t17dpr9atlqtv00t3q4grl.apps.googleusercontent.com
  GOOGLE_AUTHENTICATION_CLIENT_SECRET: QF12NyvDkbGn8VtP4y5oAoCA

LOGRAGE:
  ENABLE_RESPONSE: false

CONSTANTS:
  PAGINATION:
    DEFAULT_PER_PAGE: 100
    MAX_PER_PAGE: 1000
  CACHE_EXPIRE:
    SYNC_KEY: 1800               # Seconds
    REGISTRY: 3600               # Seconds
