name: Slack Notification Demo

on:
  push:
    branches:
      - master

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: Github Actions Bot
  SLACK_ICON_EMOJI: ':github-actions-bot:'
  SLACK_FOOTER: ''
  SLACK_CHANNEL: freelancing

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    name: Slack Notification
    steps:
    - name: Slack Deployment Started Notification
      uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_TITLE: Deployment Started

    - name: Try to fail
      run: exit 1

    - name: Slack Deployment Successful Notification
      uses: rtCamp/action-slack-notify@v2
      if: success()
      env:
        SLACK_TITLE: Successfully Deployed
        SLACK_COLOR: ${{job.status}}

    - name: Slack Deployment Failed Notification
      uses: rtCamp/action-slack-notify@v2
      if: failure()
      env:
        SLACK_TITLE: Deployment Failed
        SLACK_COLOR: ${{job.status}}

    - name: Slack Deployment Started Notification
      uses: rtCamp/action-slack-notify@v2
      if: cancelled()
      env:
        SLACK_TITLE: Deployment Cancelled
        SLACK_COLOR: ${{job.status}}
