name: Slack Notification Demo

on:
  push:
    branches:
      - master

jobs:
  slack_notification:
    name: Slack Notification
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
